aula3/aula3/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('ola/', include('ola.urls')),
    path('anonovo/', include('anonovo.urls')),
    path('tarefas/', include('tarefas.urls')),
]

aula3/ola/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:nome>', views.cumprimentar, name='cumprimentar'),
]

aula3/tarefas/urls.py
from django.urls import path
from . import views

app_name = "tarefas" 
urlpatterns = [
    path('', views.index, name='index'),
    path('adicionar/', views.adicionar, name='adicionar'),
]

aula3/anonovo/views.py
from django.shortcuts import render
from datetime import date


# Create your views here.
def index(request):
    d = "date.today().strftime('%d/%m/%Y')"
    return render(request, 'anonovo/index.html', {"resposta": "Sim!" if d.startswith('01/01') else "Não."})

aula3/aula3/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse('''
        <p><a href="/tarefas/">Tarefas</a></p>
        <p><a href="/ola/">Olá</a></p>
        <p><a href="/anonovo/">Ano novo</a></p>
        ''')

aula3/ola/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "ola/index.html")

def cumprimentar(request, nome):
    return render(request, "ola/cumprimentar.html", {"nome": nome.capitalize()})

aula3/tarefas/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NovaTarefaForm(forms.Form):
    nome_tarefa = forms.CharField(label='Nome Tarefa', max_length=100)
    descricao = forms.CharField(label='Descrição', max_length=100)
    # prazo = forms.DateField(label='Prazo')
    prioridade = forms.IntegerField(label='Prioridade', min_value = 1, max_value = 10)


# Create your views here.
def index(request):
    if "tarefas" not in request.session:
        request.session["tarefas"] = []
    return render(request, 'tarefas/index.html', {'tarefas': request.session["tarefas"]})

def adicionar(request):
    if request.method == 'POST':
        form = NovaTarefaForm(request.POST)
        if form.is_valid():
            tarefa = form.cleaned_data['nome_tarefa']
            request.session["tarefas"] += [tarefa]
            return HttpResponseRedirect(reverse('tarefas:index'))
        else:
            return render(request, 'tarefas/adicionar.html', {'form': form})

    return render(request, 'tarefas/adicionar.html', {'form': NovaTarefaForm()})

aula3/anonovo/templates/anonovo/index.html
{% extends 'ola/layout.html' %}

{% block title %} É ano novo? {% endblock %}

{% block body %}
    <h1>{{ resposta }}</h1>
{% endblock %}

aula3/ola/templates/ola/cumprimentar.html
{% extends 'ola/layout.html' %}

{% block title %} Olá! {% endblock %}

{% block body %}
    <h1>Olá, {{ nome }}</h1>
{% endblock %}

aula3/ola/templates/ola/index.html
{% extends 'ola/layout.html' %}

{% block title %} Index {% endblock %}

{% block body %}
    <h1>Bem-vindos ao index de ola</h1>
{% endblock %}

aula3/ola/templates/ola/layout.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Titulo Layout {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
      body {
        background-color: #AA4465;
      } 

      h1 {
        color: #EDF0DA;
        font-family: sans-serif;
        font-size: 90px;
        text-align: center;
      }

      /* .center {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        min-height: 100vh;
      } */
    </style>
</head>
<body>
  <main class="center">
    {% block body %}
      <h1>Corpo layout</h1>
    {% endblock %}
  </main>
</body>
</html>

aula3/tarefas/templates/tarefas/adicionar.html
{% extends 'ola/layout.html' %}

{% block title %} Adicionar {% endblock %}

{% block body %}
    <h1>Adicionar tarefa</h1>
    <form action="{% url 'tarefas:adicionar' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <p>Ver <a href="{% url 'tarefas:index' %}">tarefas</a></p>
{% endblock %}

aula3/tarefas/templates/tarefas/index.html
{% extends 'ola/layout.html' %}

{% block title %} Tarefas {% endblock %}

{% block body %}
    <ul>
    {% for tarefa in tarefas %}
        <li>{{ tarefa }}</li>
    {% empty %}
        <li>Sem tarefas.</li>
    {% endfor %}
    </ul>
    <p>Adicionar uma <a href="{% url 'tarefas:adicionar' %}">nova tarefa</a></p>
{% endblock %}